utility_meter:

##############################################################
## Totale annuo kWh Sonoff Pow r2 lavatrice ##
##############################################################  

  sonoff_pow_r2_year_energy:  # sensore diretto dal pow r2 esphome
    source: sensor.sonoff_pow_r2_total_daily_energy
    cycle: yearly
    tariffs:
      - peak            

automation:
  - alias: washing machine ending
    trigger:
      - platform: state 
        entity_id: binary_sensor.run
        from: 'on'
        to: 'off'
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.googlehome7895
          volume_level: 0.6
      - service: tts.google_translate_say
        entity_id: media_player.googlehome7895
        data_template:
          message: >
            La lavatrice ha finito
          language: 'it'
          cache: false
  - alias: washing machine start
    trigger:
      - platform: state 
        entity_id: binary_sensor.run
        from: 'off'
        to: 'on'  
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.googlehome7895
          volume_level: 0.6
      - service: tts.google_translate_say
        entity_id: media_player.googlehome7895
        data_template:
          message: >
            La lavatrice ha iniziato
          language: 'it'
          cache: false
